### PR TITLE
Make it work with concourse v7 and golang 1.16

### PR DESCRIPTION
**Pull request by combor**
## What

stopover is failing to compile on golang 1.16 and throwing such error:

```
github.com/EngineerBetter/stopover imports
    github.com/concourse/concourse/atc: cannot find module providing package github.com/concourse/concourse/atc
github.com/EngineerBetter/stopover imports
    github.com/concourse/concourse/go-concourse/concourse: cannot find module providing package github.com/concourse/concourse/go-concourse/concourse
```

we had to move vendoring method to use go mod and re-vendor all dependencies. 

This made us also to fix some tests to use newer structures form go-concourse client and fix tests.

We also had to record new responses for howerfly as it was upgraded to v5 schema and the old recording was not compatible as it was using v3.

## How to test

```
ginkgo -r -v
```

### CODE REVIEW

**Comment by crsimmons** [comment]
Hey @combor. Thanks for the PR!

Have you tested this change on older versions of Concourse (v5 or v6)? We've had issues in the past where the changes to make stopover work for Concourse v5+ didn't work with earlier versions.

**Comment by combor** [comment]
I haven't tested this as we don't have any v5/6 left any more.

**Comment by StuWill** [comment]
Hey @crsimmons :) 
We will need to change this pr now as our recent merge to our forked repo's master branch has updated this pr. We will close and reopen a new one from a branch in our forked repo.

**Comment by combor** [comment]
https://github.com/EngineerBetter/stopover/pull/6
