### PR TITLE
Make it work with concourse v7 and golang 1.16

### PR DESCRIPTION
**Pull request by combor**
## What

stopover is failing to compile on golang 1.16 and throwing such error:

```
github.com/EngineerBetter/stopover imports
    github.com/concourse/concourse/atc: cannot find module providing package github.com/concourse/concourse/atc
github.com/EngineerBetter/stopover imports
    github.com/concourse/concourse/go-concourse/concourse: cannot find module providing package github.com/concourse/concourse/go-concourse/concourse
```

we had to move vendoring method to use go mod and re-vendor all dependencies. 

This made us also to fix some tests to use newer structures form go-concourse client and fix tests.

We also had to record new responses for howerfly as it was upgraded to v5 schema and the old recording was not compatible as it was using v3.

## How to test

```
ginkgo -r -v
```

### CODE REVIEW

**Comment by crsimmons** [comment]
I've tested this on Concourse 5.8.1 and 6.7.4 and it appears to work. @BooleanCat confirmed the tests passed earlier. LGTM 🚢

**Comment by BooleanCat** [comment]
Thanks for the work on this, appreciated @combor!

**Comment by BooleanCat** [comment]
I've shipped [v2.0.1](https://github.com/EngineerBetter/stopover/releases/tag/v2.0.1) with this change.
